#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2019-03-17 08:02:41.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("data_frame_to_paths() works", {

  expect_error(
    kwb.pathdict:::data_frame_to_paths()
    # argument "df" is missing, with no default
  )

})

