#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2019-03-17 08:02:40.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_next_level() works", {

  expect_error(
    kwb.pathdict:::get_next_level()
    # 'split_paths' is not an exported object from 'namespace:kwb.file'
  )

})

