#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2019-03-17 08:02:41.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("use_dictionary() works", {

  expect_error(
    kwb.pathdict:::use_dictionary()
    # argument "x" is missing, with no default
  )

})

