#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2019-03-17 08:02:40.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("to_dictionary_key() works", {

  expect_error(
    kwb.pathdict:::to_dictionary_key()
    # argument "i" is missing, with no default
  )

})

